### ISSUE TITLE
Error relocating /lib/libtg_owt.so.0: crc32c_value: symbol not found

### ISSUE THREAD

**Issue by kingfared** [desktop-app/tg_owt#116]
https://github.com/desktop-app/tg_owt/blob/5098730b9eb6173f0b52068fe2555b7c1015123a/cmake/external.cmake#L173

On Gentoo Telegram fails to start with error. Changing type from INTERFACE to PRIVATE fixes it.

**Comment by Petrprogs** [comment]
Did you run ```git submodule update --init --recursive``` in repo dir?
