### ISSUE TITLE
Missing libyuv files

### ISSUE THREAD

**Issue by raghavgururajan** [desktop-app/tg_owt#42]
While building latest master, the build fails with missing libyuv files. It turns out the directory 'src/third_party/libyuv' is empty.

**Comment by raghavgururajan** [comment]
As a work-around, I have been building from the commit 10b988aa9111fd25358443ac34d0d422b5108029 in master. But this seems to causing https://github.com/telegramdesktop/tdesktop/issues/10113

**Comment by 23rd** [comment]
Please read the instructions more carefully.

**Comment by raghavgururajan** [comment]
@23rd Could you please provide me a link to it. I could not find the README file for this repository.

**Comment by 23rd** [comment]
The build instructions for this repository can be found in the TDesktop repository.

**Comment by raghavgururajan** [comment]
I looked at this (https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md). For my use case, I don't think its applicable. I am packaging tdesktop for Guix (https://guix.gnu.org), which is a non-conventional distro.

But I have a way to re-build tg_owt with sub-modules. So all good. :-)
