### ISSUE TITLE
build failure due to protobuf compatibility

### ISSUE THREAD

**Issue by xloem** [desktop-app/tg_owt#43]
```
[ 28%] Running cpp protocol buffer compiler on /shared/src/tg_owt/src/logging/rtc_event_log/rtc_event_log.proto
rtc_event_log.proto:51:3: Expected "required", "optional", or "repeated".
rtc_event_log.proto:51:17: Missing field number.
make[2]: *** [cmake/protobuf/CMakeFiles/proto.dir/build.make:82: cmake/protobuf/rtc_event_log.pb.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:622: cmake/protobuf/CMakeFiles/proto.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```
```
$ protoc --version
libprotoc 2.5.0
```

**Comment by ilya-fedin** [comment]
Shared build is community maintained. You should fix it yourself and PR the fix.

**Comment by xloem** [comment]
That's a great answer, and that information should go in a readme.  I notice there are no comments on #35 .    Is anybody available to enable [auto-merge](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request)?  That could really make community maintenance work.

**Comment by xvitaly** [comment]
@xloem On Fedora we use protobuf 3.14.0. Please try to upgrade your protobuf compiler.

**Comment by john-preston** [comment]
I hope an updated version of protobuf fixes this issue.
