### ISSUE TITLE
Build fails on armv7

### ISSUE THREAD

**Issue by ggardet** [desktop-app/tg_owt#48]
Build fails on armv7 with the following error:
```
[  156s] -- ARM Architecture version is 7.
[  156s] -- NEON SIMD instructions enabled (can be disabled with -DTG_OWT_ARCH_ARMV7_USE_NEON=OFF).
[  158s] -- Configuring done
[  158s] CMake Error at cmake/libvpx.cmake:1 (add_library):
[  158s]   Cannot find source file:
[  158s] 
[  158s]     /home/abuild/rpmbuild/BUILD/Libraries/tg_owt/src/third_party/libvpx/source/libvpx/vpx_dsp/arm/intrapred_neon_asm.asm.S
```

`intrapred_neon_asm.asm.S` does not exist, but `intrapred_neon_asm.asm` is there.

**Comment by ilya-fedin** [comment]
Only x86_64 build is really maintained. ARM build was introduced by @dusxmt, but looks like he is not interested in maintaining it.

**Comment by dusxmt** [comment]
I will look into it tomorrow.

**Comment by dusxmt** [comment]
From the error message itself, it seems like all that needs to be done is the file file listing in the build system needs to be updated - unfortunately, it's not performed automatically when the third party libraries get updated.

**Comment by ilya-fedin** [comment]
> From the error message itself, it seems like all that needs to be done is the file file listing in the build system needs to be updated

From what I digged, previously it was fetched by gclient and prepared by some commands. One of these commands is https://github.com/desktop-app/tg_owt/blob/a19877363082da634a3c851a4698376504d2eaee/src/third_party/libvpx/BUILD.gn#L263-L286

Probably this should be integrated into cmake build somehow, just like yasm.

**Comment by dusxmt** [comment]
Indeed, most likely a [add_custom_command()](https://cmake.org/cmake/help/latest/command/add_custom_command.html#command:add_custom_command) statement would be appropriate to generate the .S files for gcc, I'll try and see if I can get it running.

**Comment by dusxmt** [comment]
Hey @ggardet, sorry for the long wait, could you test https://github.com/desktop-app/tg_owt/pull/53 out to see if it helps?  It should fix the libvpx build failure, but I don't currently have an easy way to test whether the entire build finishes successfully (there's some problem with protobuf that causes the build to eventually fail on my system)

**Comment by pheiduck** [comment]
On X86:
```bash
FAILED: CMakeFiles/tg_owt.dir/gen/pipewire_stubs.cc.o 
/usr/bin/c++ -DABSL_ALLOCATOR_NOTHROW=1 -DBWE_TEST_LOGGING_COMPILE_TIME_ENABLE=0 -DHAVE_NETINET_IN_H -DHAVE_SCTP -DHAVE_WEBRTC_VIDEO -DNO_MAIN_THREAD_WRAPPING -DRTC_DISABLE_TRACE_EVENTS -DRTC_ENABLE_VP9 -DWEBRTC_APM_DEBUG_DUMP=0 -DWEBRTC_DLOPEN_PIPEWIRE -DWEBRTC_ENABLE_LINUX_ALSA -DWEBRTC_ENABLE_LINUX_PULSE -DWEBRTC_ENABLE_PROTOBUF=0 -DWEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE -DWEBRTC_LIBRARY_IMPL -DWEBRTC_LINUX -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=1 -DWEBRTC_OPUS_SUPPORT_120MS_PTIME=1 -DWEBRTC_OPUS_VARIABLE_COMPLEXITY=0 -DWEBRTC_POSIX -DWEBRTC_USE_BUILTIN_ISAC_FLOAT -DWEBRTC_USE_H264 -DWEBRTC_USE_PIPEWIRE -DWEBRTC_USE_X11 -Igen -I../src/third_party/pipewire/spa/include -I../src/third_party/pipewire/src -I../src/third_party/pipewire/build/src -I/usr/include/opus -I../src/third_party/openh264/src/include -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I../src -I../src/third_party/pffft/src -I../src/third_party/libsrtp/include -I../src/third_party/libsrtp/crypto/include -I../src/third_party/libyuv/include -I../src/third_party/abseil-cpp -Iopenh264_include -I../src/third_party/usrsctp/usrsctplib -I../src/third_party/usrsctp/usrsctplib/usrsctplib -I../src/third_party/libvpx/source/libvpx -I../src/third_party/libvpx/source/config -I../src/third_party/libvpx/source/config/linux/x64 -I../src/base/third_party/libevent -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -O3 -DNDEBUG -Wno-deprecated-declarations -Wno-attributes -Wno-narrowing -Wno-return-type -MD -MT CMakeFiles/tg_owt.dir/gen/pipewire_stubs.cc.o -MF CMakeFiles/tg_owt.dir/gen/pipewire_stubs.cc.o.d -o CMakeFiles/tg_owt.dir/gen/pipewire_stubs.cc.o -c gen/pipewire_stubs.cc
In file included from gen/pipewire_stubs.cc:18:
../src/third_party/pipewire/src/pipewire/pipewire.h:61:10: fatal error: pipewire/version.h: No such file or directory
   61 | #include <pipewire/version.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by john-preston** [comment]
Works now in Snap build.

**Comment by ggardet** [comment]
> Works now in Snap build.

I confirm it builds fine now. Thanks!
