### ISSUE TITLE
[REQUEST]: Option to use packaged third_party

### ISSUE THREAD

**Issue by raghavgururajan** [desktop-app/tg_owt#52]
Requesting an option to use packaged (distribution-provided) version of third-parties, instead of building from `src/third_party`.

**Comment by ilya-fedin** [comment]
Well, you can work on this if you need this.

**Comment by raghavgururajan** [comment]
Yes, I just wanted to post here, so that if anyone else is interested and beat me to it. :-)

**Comment by mid-kid** [comment]
I'll try to work on this, but it'd be nice to know if things like libvpx, libyuv, etc have some version requirement - there's files in here for version 1.8.2, yet the submodule is v1.9.0+git...

**Comment by ilya-fedin** [comment]
> but it'd be nice to know if things like libvpx, libyuv, etc have some version requirement

:thinking: probably this should be documented at google's webrtc documentation?

**Comment by raghavgururajan** [comment]
> Well, you can work on this if you need this.

Oops! Sorry, I missed your message @ilya-fedin . I am afraid I don't know how to do it.

**Comment by raghavgururajan** [comment]
> I'll try to work on this, but it'd be nice to know if things like libvpx, libyuv, etc have some version requirement - there's files in here for libvpx version 1.8.2, yet the submodule is v1.9.0+git...

@mid-kid Thanks a lot for working on this. :-)
