### ISSUE TITLE
Incompatibility with FFMPEG >=4.2.x (devel) - Invalid conversion from 'const AVCodec*' to 'AVCodec*'  

### ISSUE THREAD

**Issue by EndlessEden** [desktop-app/tg_owt#64]
/src/modules/video_coding/codecs/h264/h264_decoder_impl.cc:205:40: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]

versions of FFMPEG newer than 4.2 fail to be built against. For reference, from a unrelated project (https://github.com/dmlc/decord/pull/160)

[I have a terrible headache, so please ignore any mistakes]

**Comment by ilya-fedin** [comment]
builds just fine with tdesktop's dockerfile that has ffmpeg 4.4

**Comment by zuowanbushiwo** [comment]
@ilya-fedin  Where can I find tdesktop's dockerfile, can you give me a link?

**Comment by MarshalX** [comment]
> @ilya-fedin Where can I find tdesktop's dockerfile, can you give me a link? thanks

https://github.com/telegramdesktop/tdesktop/blob/1b3075ac2eea8bb4925d16085d7a0655773e3245/Telegram/build/docker/centos_env/Dockerfile#L382

**Comment by ilya-fedin** [comment]
Can we close the issue?

**Comment by EndlessEden** [comment]
I apologize, been extremely busy...

This specific issue is resolved; Building against 4.4.0
