### ISSUE TITLE
Build fails against FFmpeg 4.4.2+; cannot initialize a variable of type 'AVCodec *' with an rvalue of type 'const AVCodec *' | Depreciated function removal

### ISSUE THREAD

**Issue by EndlessEden** [desktop-app/tg_owt#72]
Attempting to build against FFmpeg (4.4.1-9fd2b39428) fails.

In member function ‘virtual int32_t webrtc::H264DecoderImpl::InitDecode(const webrtc::VideoCodec*, int32_t)’:
src/modules/video_coding/codecs/h264/h264_decoder_impl.cc:205:40: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]

**Comment by EndlessEden** [comment]
commit version in reference: https://github.com/FFmpeg/FFmpeg/commit/9fd2b39428

**Comment by ilya-fedin** [comment]
Feel free to fix that yourself if you really need that

**Comment by EndlessEden** [comment]
Sorry, million other things im catching up on.

Yes, im using master, the depreciated api calls that were depreciated back in ffmpeg-3.1 are being removed in the next release (coming afaik in Q1-2022, so rather soon).

My projects that rely on tg_owt will be non-functional soon, and i submitted this bug request pre-emptively before the release.

None of the issues this bug request is relative to unstable api changes in 4.4.2+, but rather depreciation from 3.1-4.0 that are now officially removed for next version.

**Comment by ilya-fedin** [comment]
Well, no development happens in this repo, this repo provides cmake files for the Google WebRTC library. If your bug is related to the code, you should report it upstream, not here.
