### ISSUE TITLE
undefined reference to `vtable for dcsctp::TextPcapPacketObserver'

### ISSUE THREAD

**Issue by svenstaro** [desktop-app/tg_owt#75]
Hey, I'm the Arch Linux maintainer for Telegram and I'm trying to compile Telegram Desktop 3.3.0 for it. I'm using tg_owt d5c3d43 as a base. [This](https://github.com/archlinux/svntogit-community/blob/b529c6a84c0e56c9bb176a4cf1e163fa02111a87/trunk/PKGBUILD) is how I build tg_owt and [this](https://github.com/archlinux/svntogit-community/blob/eae8f3aa45a6fc7dfdf6b3f7bcbc212603b63f8a/trunk/PKGBUILD) is how I build Telegram Desktop.

Everything seems fine until link time where I get:
```
/usr/bin/ld: /usr/lib/libtg_owt.so.0.0.0: undefined reference to `dcsctp::TaskQueueTimeoutFactory::TaskQueueTimeout::TaskQueueTimeout(dcsctp::TaskQueueTimeoutFactory&)'
/usr/bin/ld: /usr/lib/libtg_owt.so.0.0.0: undefined reference to `dcsctp::DcSctpSocketFactory::Create(std::basic_string_view<char, std::char_traits<char> >, dcsctp::DcSctpSocketCallbacks&, std::unique_ptr<dcsctp::PacketObserver, std::default_delete<dcsctp::PacketObserver> >, dcsctp::DcSctpOptions const&)'
/usr/bin/ld: /usr/lib/libtg_owt.so.0.0.0: undefined reference to `vtable for dcsctp::TextPcapPacketObserver'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

I'm posting this here and not on the tdesktop repository as I believe there's something wrong with tg_owt.

[Full tdesktop log](https://github.com/desktop-app/tg_owt/files/7682490/tdesktop.txt)
[Full tg_owt log](https://github.com/desktop-app/tg_owt/files/7682495/tg_owt.txt)
Built via gcc 11.1.0.

Any hints? I believe I'm building everything correctly and tg_owt doesn't bark any missing dependencies or such.

**Comment by perestoronin** [comment]
to temprary fix this case use -DBUILD_SHARED_LIBS=OFF

**Comment by svenstaro** [comment]
I suppose I could do that but it doesn't seem like a proper fix.

**Comment by ilya-fedin** [comment]
Building as shared library is community supported and is not guaranteed to work. You can PR a fix or wait until someone else interested PR a fix.

**Comment by mikhailnov** [comment]
Have a look at https://abf.io/import/telegram-desktop/tree/rosa2021.1 , where tg_owt is built inside tdesktop and then tdesktop is linked to it statically as officially supported. A separate package with tg_owt does not make sense for now. But you can convert it from a shared library to a static one and it will become abuildtime only dependency of tdesktop, not runtime one.

**Comment by mikhailnov** [comment]
Of course it would be better to build tg_owt as a shred library but will anyone want to deal with it in that strange upstream...

**Comment by perestoronin** [comment]
> 

simplest solution to build with shared linked

https://github.com/gentoo/gentoo/blob/master/media-libs/tg_owt/files/tg_owt-0_pre20211207-fix-dcsctp-references.patch

**Comment by svenstaro** [comment]
Perhaps that should be upstreamed @perestoronin
