### ISSUE TITLE
Build error with clang-13

### ISSUE THREAD

**Issue by mid-kid** [desktop-app/tg_owt#83]
```
/var/tmp/portage/media-libs/tg_owt-0_pre20211207/work/tg_owt-d5c3d43b959c7e9e7d8004b9b7fdadd12ce7d589/src/modules/congestion_controller/goog_cc/loss_based_bwe_v2.cc:288:10: error: no matching member function for call to 'emplace'
  config.emplace();
  ~~~~~~~^~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/g++-v11/optional:868:2: note: candidate template ignored: requirement 'is_constructible_v<webrtc::LossBasedBweV2::Config>' was not satisfied [with _Args = <>]
        emplace(_Args&&... __args)
        ^
/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/g++-v11/optional:879:2: note: candidate function template not viable: requires at least argument '__il', but no arguments were provided
        emplace(initializer_list<_Up> __il, _Args&&... __args)
        ^
1 error generated.
```

I'm not sure how to even begin solving this, nor why it was introduced in this version of clang.

https://bugs.gentoo.org/830845

**Comment by msva** [comment]
btw, I also tried with clang-12, and there were same error.

I'd bet on problems on GCC's side.

// btw, building with libcxx is kinda unlikely way to "fix issue", as it will require to build a tons of stuff (of tdesktop deps) with libcxx too. When it gone for glib, I given up...

**Comment by mymedia2** [comment]
On Пн, 2022-02-14 at 01:10 -0800, Vadim A. Misbakh-Soloviov wrote:
> I'd bet on problems on GCC's side.

That's an interesting approach. GCC compiles this code just fine, but
you suspect problems in GCC. 😂

**Comment by mid-kid** [comment]
GCC supplies libstdc++ which clang can (and by default does) link against. It's not a crazy idea.
